---
- name: how to prompt for variables
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "yourpasswordvar"
      prompt: "What is your password? " 
      private: yes ## does not echo your password
      encrypt: "sha512_crypt"
      confirm: yes
      

  
  tasks:
   - name: show the results
     debug:
       var: yourpasswordvar
